- name: 'bug'
  color: 'd73a4a'
  description: "Something isn't working"
- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'
- name: 'duplicate'
  color: 'cfd8d7'
  description: 'This issue or pull request already exists'
- name: 'cicd'
  color: 'd4c5f9'
  description: 'CI CD related stuffs'
- name: 'tech'
  color: '5A1674'
  description: 'Tech updated'
- name: 'security'
  color: 'D39830'
  description: 'Security related stuffs'
- name: 'docs'
  color: '5319e7'
  description: 'Documentations'
- name: 'performance'
  color: 'C24B13'
  description: 'Performance update'
- name: 'test'
  color: '651AA7'
  description: 'Tests'
- name: 'bugfix'
  color: '3A6E6F'
  description: 'Bug Fix'
- name: 'feature'
  color: '1163A7'
  description: 'Feature'
- name: 'enhancement'
  color: 'a22eef'
- name: 'dependencies'
  color: '4FB22E'
- name: 'wontfix_it'
  color: '08A6C5'
  description: 'This will not be worked on'
  from_name: 'wontfix'
